name: Compile Firmware

on:
  push:
    branches:
    - sn32
    - sn32_openrgb
    - sn32_openrgb_new
  pull_request:
    branches:
    - sn32
    - sn32_openrgb
    - sn32_openrgb_new

jobs:
  Build:
    runs-on: ubuntu-latest

    container: jath03/sonix_base_container

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Build keyboards
      run: python3 bin/build_all.py
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF_NAME//\//-})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Pre-Compiled Firmware (${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }})
        path: '*.bin'
        
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Pre-Compiled Firmware
        path: '*.bin'
